apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: bucket-composition-1
spec:
  compositeTypeRef:
    apiVersion: s3.example.org/v1alpha1
    kind: XBucket
  
  resources:
  - name: queue
    base:
      apiVersion: sqs.aws.crossplane.io/v1beta1
      kind: Queue
      metadata:
        name: # patched
      spec:
        forProvider:
          region: eu-central-1
          delaySeconds: 4
          policy: |
            {
              "Version": "2012-10-17",
              "Id": "allow-s3",
              "Statement": [
                {
                  "Sid": "allow-s3",
                  "Effect": "Allow",
                  "Principal": {
                    "Service": "s3.amazonaws.com"
                  },
                  "Action": [
                    "SQS:SendMessage"
                  ],
                  "Resource": "*",
                  "Condition": {
                    "ArnLike": {
                      "aws:SourceArn": "arn:aws:s3:*:*:*"
                    }
                  }
                }
              ]
            }
        providerConfigRef:
          name: default
    patches:
      - fromFieldPath: metadata.labels['crossplane.io/claim-name']
        toFieldPath: metadata.name
      - type: ToCompositeFieldPath
        fromFieldPath: status
        toFieldPath: status.resources.queue
  - name: bucket-v2
    base:
      apiVersion: s3.aws.crossplane.io/v1beta1
      kind: Bucket
      metadata:
        name: # patched
      spec:
        forProvider:
          objectOwnership: BucketOwnerEnforced
          locationConstraint: eu-central-1
          notificationConfiguration:
            queueConfigurations:
              - events: [] # patched
                queueArn: # patched
        providerConfigRef:
          name: default
    patches:
      - fromFieldPath: metadata.labels['crossplane.io/claim-name']
        toFieldPath: metadata.name
      - fromFieldPath: status.resources.queue.atProvider.arn
        toFieldPath: spec.forProvider.
      - type: ToCompositeFieldPath
        fromFieldPath: status
        toFieldPath: status.resources.bucket