apiVersion: meta.pkg.crossplane.io/v1
kind: Configuration
metadata:
  name: example-configuration
spec:
  crossplane:
    version: ">=v1.13.2"
  dependsOn:
    - provider: crossplanecontrib/provider-aws
      version: ">=v0.42.0"
    - provider: crossplanecontrib/provider-kubernetes
      version: ">=v0.9.0"
