apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xbuckets.s3.example.org
spec:
  group: s3.example.org
  names:
    kind: XBucket
    plural: xbuckets
  claimNames:
    kind: Bucket
    plural: buckets
  versions:
  - name: v1alpha1
    served: true
    referenceable: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              notificationEvents:
                type: array
                items:
                  type: string
          status:
            type: object
            properties:
              resources:
                type: object
                x-kubernetes-preserve-unknown-fields: true
        required:
          - spec